version: "3.6"
services:
    prometheus-xeus-prod:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9090:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-xeus-prod.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/phoenix/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule              
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix 
    prometheus-dev:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9091:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/phoenix/dev/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule              
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix    

    prometheus-odin-prod:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9092:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-odin-prod.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/odin/prod/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule            
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix    
    prometheus-saturn-prod:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9093:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-saturn-prod.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/saturn/prod/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule              
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix      
    prometheus-searchad-prod:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9094:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-searchad-prod.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/searchad/prod/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule              
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix                           
    prometheus-cafertb:
        image: repo.sabacell.net:5000/prometheus:latest
        hostname: prometheus
        ports:
            - "9095:9090"
        volumes:
            - /etc/localtime:/etc/localtime:ro 
            - /config/monitoring/prometheus/config/phoenix/prometheus-cafertb-integration.yml:/etc/prometheus/prometheus.yml:ro
            - /data/monitoring/prometheus/cafertb/prod/data:/prometheus
            - /config/monitoring/prometheus/config/rules/nginx.alert.rule:/etc/prometheus/nginx.alert.rule
            - /config/monitoring/prometheus/config/rules/nginx.counter.rule:/etc/prometheus/nginx.counter.rule
            - /config/monitoring/prometheus/config/rules/nginx.errrate.rule:/etc/prometheus/nginx.errrate.rule
            - /config/monitoring/prometheus/config/rules/nginx.latency.rule:/etc/prometheus/nginx.latency.rule
            - /config/monitoring/prometheus/config/rules/nginx.qps.rule:/etc/prometheus/nginx.qps.rule              
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                       
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            - phoenix   
    grafana:
        #image: repo.sabacell.net:5000/grafana:7.4.0
        image: repo.sabacell.net:5000/grafana:7.4.0-image-rendering
        image: repo.sabacell.net:5000/grafana:10
        hostname: grafana
        # ports:
        #    - "3000:3000"
        #environment:
            #- GF_SMTP_ENABLED="true"
            #- GF_SMTP_HOST="smtp.zoho.com:587"
            #- GF_SMTP_USER="monitoring@sabacell.ir"
            #- GF_SMTP_PASSWORD= B$$@zp:/Vuzg6LV'V
            #- GF_SMTP_SKIP_VERIFY="false"
            #- GF_SMTP_FROM_ADDRESS="monitoring@sabacell.ir"
            
        volumes:
            - /data/monitoring/grafana/phoenix/lib/:/var/lib/grafana
            - /config/monitoring/grafana/conf/phoenix/defaults.ini:/usr/share/grafana/conf/defaults.ini
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5                    
        logging:
            driver: "json-file"
            options:
                max-size: "50m"                  
        networks:
            phoenix:
                aliases:
                    - monitoring.phoenixad.io
    apitester:
        image: repo.sabacell.net:5000/paroo.postmanexporter:latest
        hostname: postmanexporter
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - PAROO_NLOG_CONFIG_PATH=/paroo-nlog.config
            - PAROO_LOG_APPNAME=paroo-postmanexporter
            - PAROO_LOGLEVEL=Warn
            - PAROO_LOGDIRECTORY=/paroo-logs
        #ports:
        #    - "9669:80"
        volumes:
            - /config/monitoring/apitester/collections:/postman/collections
            - /config/monitoring/apitester/nlog.config:/paroo-nlog.config
        deploy:
            replicas: 1
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
        # logging:
        #     driver: "fluentd"
        #     options:
        #         fluentd-address: localhost:24225
        #         tag: paroo-postmanexporter
        #         fluentd-async-connect: "true"  
        logging:
            driver: "json-file"
            options:
                max-size: "50m"   
        networks:
            - phoenix
######################################## This service is not required yet ###############################
#    grafana-data-exporter:
#        image: repo.sabacell.net:5000/grafana-data-exporter:latest
#        # ports:
#        #     - "8000:8000"
#        volumes:
#            - /config/monitoring/grafana-data-exporter/phoenix/exported:/var/www/exported
#            - /config/monitoring/grafana-data-exporter/phoenix/config.json:/var/www/config.json
#            #- /config/monitoring/grafana-data-exporter/etc/hosts:/etc/hosts
#            - /config/monitoring/grafana-data-exporter/phoenix/var/www/dist/server.js:/var/www/dist/server.js
#        deploy:
#            restart_policy:
#                condition: any
#                delay: 5s
#                max_attempts: 5
#        logging:
#            driver: "json-file"
#            options:
#                max-size: "50m"  
#        networks:
#            phoenix:
#                aliases:
#                    - grafanaexporter.sabacell.net
networks:
    phoenix:
        external: true   
